[project]
name = "ppt-to-txt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "pdf2image>=1.17.0",
    "pillow>=11.2.1",
    "pydantic-ai-slim[openai]>=0.2.16",
]
